export const alimentsList = [
    { id: 1, imageFile: "jus_dorange", fr: "jus d'orange", pt: "suco de laranja", tip: "c'est une boisson à base de fruits", isClicked: false },
    { id: 2, imageFile: "pain_de_fromage", fr: "pain au fromage", pt: "pão de queijo", tip: "c'est un plat brésilien d'origine Mineira", isClicked: false },
    // { id: 3, imageFile: "croque_monsieur", fr: "croque-monsieur brésilien", pt: "misto quente", tip: "c'est un sandwich grillé au jambon et fromage", isClicked: false },
    // { id: 4, imageFile: "oeufs_brouilles", fr: "œufs brouillés", pt: "ovo mexido", tip: "ce sont des œufs cuits et mélangés", isClicked: false },
    { id: 5, imageFile: "couscous_de_mais", fr: "couscous de mais", pt: "cuscuz (nordestino)", tip: "c'est un plat à base de semoule de maïs", isClicked: false },
    // { id: 7, imageFile: "queijo_minas", fr: "fromage Minas", pt: "queijo minas", tip: "c'est un type de fromage brésilien", isClicked: false },
    { id: 8, imageFile: "pain_grille", fr: "pain grillé avec du beurre", pt: "pão na chapa com manteiga", tip: "c'est du pain grillé avec du beurre", isClicked: false },
    { id: 9, imageFile: "confiture_de_fraise", fr: "confiture de fraise", pt: "geleia de morango", tip: "c'est une confiture de fruits rouges", isClicked: false },
    // { id: 10, imageFile: "beignet_de_pluie", fr: "beignet de pluie", pt: "bolinho de chuva", tip: "c'est un petit beignet frit", isClicked: false },
    { id: 11, imageFile: "tartine", fr: "tartine", pt: "torrada", tip: "c'est du pain grillé", isClicked: false },
    // { id: 12, imageFile: "lait_achocolate", fr: "lait chocolaté", pt: "leite achocolatado", tip: "c'est une boisson lactée au chocolat", isClicked: false },
    { id: 13, imageFile: "tasse_de_cafe", fr: "café", pt: "café", tip: "c'est une boisson chaude à base de grains torréfiés", isClicked: false },
    { id: 14, imageFile: "jambon", fr: "tranches de jambon", pt: "fatias de presunto)", tip: "ça vient du porc", isClicked: false },
    { id: 15, imageFile: "gateau_au_citron", fr: "gâteau au citron", pt: "bolo de limão", tip: "c'est un gâteau parfumé au citron", isClicked: false },
    { id: 16, imageFile: "cereales", fr: "bol de céréales", pt: "tigela de cereais", tip: "ce sont des céréales pour le petit-déjeuner", isClicked: false },
    { id: 17, imageFile: "bouillie_davoine", fr: "bouillie d'avoine à la cannelle", pt: "mingau de aveia com canela", tip: "c'est une bouillie d'avoine chaude", isClicked: false },
    { id: 6, imageFile: "tapioca", fr: "tapioca à la noix de coco", pt: "tapioca recheada com coco", tip: "c'est une crêpe de tapioca à la noix de coco", isClicked: false },
];